Repository medusajs/admin, pull requests merged in 2022-02, with the labels that each got.

#286 Fix/order filter control
  package.json
  src/components/filter-dropdown-item/index.js
  src/components/fundamentals/input-header.tsx
  src/components/molecules/filter-dropdown/item.tsx
  src/components/molecules/table/index.tsx
  src/components/templates/order-filter-dropdown/index.tsx
  src/components/templates/order-table/index.tsx
  src/components/templates/order-table/use-order-filters.ts
  src/domain/orders/filter-dropdown.js
  src/domain/orders/index-legacy.js
  src/domain/orders/index.tsx
  src/utils/time.js
  yarn.lock
Labels: in review: oli

#333 feat: add hook to highlight search terms
  src/components/molecules/table/index.tsx
  src/hooks/use-highlight-search.tsx
Labels: type: feature or enhancement

#345 fix: Mark swap + claim fulfillments as shipped
  src/domain/orders/details/index.tsx
  src/domain/orders/details/mark-shipped/index.tsx
  src/domain/orders/details/templates/fulfillment.tsx
  src/hooks/use-build-timeline.tsx
Labels: type: bug

#320 Fix/timeline modals
  src/components/layout/popover.js
  src/components/molecules/modal/index.tsx
  src/components/molecules/rma-select-shipping/index.tsx
  src/components/molecules/tag-input/index.tsx
  src/components/molecules/timeline-events/claim/details.tsx
  src/components/molecules/timeline-events/claim/index.tsx
  src/components/molecules/timeline-events/event-container.tsx
  src/components/molecules/timeline-events/exchange.tsx
  src/components/molecules/timeline-events/items-fulfilled.tsx
  src/components/molecules/timeline-events/items-shipped.tsx
  src/components/molecules/timeline-events/refund.tsx
  src/components/molecules/timeline-events/return.tsx
  src/components/organisms/rma-return-product-table/index.tsx
  src/components/organisms/rma-select-product-table/index.tsx
  src/components/organisms/timeline/index.tsx
  src/components/private-route/index.js
  src/components/templates/draggable-table.tsx
  src/domain/orders/details/create-fulfillment/index.tsx
  src/domain/orders/details/mark-shipped/index.tsx
  src/domain/orders/details/returns/receive-menu.tsx
  src/domain/products/details/index.js
  src/hooks/use-build-timeline.tsx
Labels: type: feature or enhancement

#323 feat: Add images section to Gift Card overview
  src/domain/gift-cards/manage/index.tsx
  src/domain/gift-cards/manage/use-gift-card-image-columns.tsx
  src/domain/gift-cards/new.tsx
Labels: type: feature or enhancement

#329 feat: update collection products
  src/components/molecules/indeterminate-checkbox/index.tsx
  src/components/organisms/add-product-modal/index.tsx
  src/components/templates/collection-product-table/add-product-table.tsx
  src/components/templates/collection-product-table/view-products-table.tsx
  src/domain/collections/details/index.tsx
  src/services/api.js
Labels: type: feature or enhancement

#347 feat: add global search
  src/components/atoms/os-shortcut/index.tsx
  src/components/atoms/text-input/index.tsx
  src/components/atoms/tooltip/index.tsx
  src/components/fundamentals/icons/down-left/down-left-icon.stories.tsx
  src/components/fundamentals/icons/down-left/index.tsx
  src/components/fundamentals/icons/pointer-icon/index.tsx
  src/components/fundamentals/icons/pointer-icon/pointer-icon.stories.tsx
  src/components/molecules/search-bar.tsx
  src/components/templates/search-modal/index.tsx
  src/components/templates/search-modal/keyboard-shortcuts.tsx
  src/components/templates/search-modal/results/customer-results.tsx
  src/components/templates/search-modal/results/discount-results.tsx
  src/components/templates/search-modal/results/order-results.tsx
  src/components/templates/search-modal/results/product-results.tsx
  src/components/templates/search-modal/section-collapsible.tsx
  src/components/templates/search-modal/use-keyboard-navigation-list.tsx
  tailwind.config.js
Labels: type: feature or enhancement
